// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package tickets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/VladanT3/IT_Ticketing_Platform/models"
	"github.com/VladanT3/IT_Ticketing_Platform/views/layouts"
)

func TicketSearch(current_user models.Analyst, user_type string, search_type string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto mt-5 flex flex-col\"><div class=\"flex flex-col\"><h1 class=\"text-2xl mb-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(search_type)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/tickets/ticket_search.templ`, Line: 12, Col: 43}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><hr></div><div class=\"grid grid-cols-5 mt-3\"><div class=\"col-span-1 grid grid-cols-5\"><form hx-post=\"/tickets/filter\" hx-trigger=\"submit\" hx-swap=\"innerHTML\" hx-target=\"#tickets\" class=\"col-span-4 flex flex-col\"><input type=\"hidden\" name=\"search_type\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(search_type)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/tickets/ticket_search.templ`, Line: 18, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><div class=\"flex flex-col mt-3\"><label>Search:</label> <input type=\"text\" name=\"search\" class=\"uk-input text-zinc-50 text-base\"></div><div class=\"flex flex-col mt-3\"><label>Customer Search:</label> <input type=\"text\" name=\"customer\" class=\"uk-input text-zinc-50 text-base\"></div><div class=\"flex flex-col mt-3\"><label>Type:</label> <label><input type=\"radio\" name=\"type\" value=\"Both\" class=\"uk-checkbox border rounded-full border-zinc-50\" checked> Both</label> <label><input type=\"radio\" name=\"type\" value=\"Request\" class=\"uk-checkbox border rounded-full border-zinc-50\"> Request</label> <label><input type=\"radio\" name=\"type\" value=\"Incident\" class=\"uk-checkbox border rounded-full border-zinc-50\"> Incident</label></div><div class=\"flex flex-col mt-3\"><label>Status:</label> <label><input type=\"radio\" name=\"status\" value=\"Both\" class=\"uk-checkbox border rounded-full border-zinc-50\" checked> Both</label> <label><input type=\"radio\" name=\"status\" value=\"Open\" class=\"uk-checkbox border rounded-full border-zinc-50\"> Open</label> <label><input type=\"radio\" name=\"status\" value=\"Closed\" class=\"uk-checkbox border rounded-full border-zinc-50\"> Closed</label></div><div class=\"flex flex-col mt-3\"><label>Category:</label> <select name=\"category\" class=\"uk-select text-zinc-50\" hx-get=\"/subcategories/get/select\" hx-target=\"#subcategories\" hx-swap=\"outerHTML\" hx-trigger=\"change\"><option value=\"none\">Choose one...</option> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, category := range models.GetAllCategories() {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<option value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(category.Category_ID.String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/tickets/ticket_search.templ`, Line: 44, Col: 54}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(category.Category_Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/tickets/ticket_search.templ`, Line: 44, Col: 81}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</option>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</select></div><div class=\"flex flex-col mt-3\"><label>Subcategory:</label> <select name=\"subcategory\" id=\"subcategories\" class=\"uk-select text-zinc-50\" disabled><option value=\"none\">Please select a category</option></select></div><div class=\"mt-3\"></div><div class=\"mt-3\"><button type=\"submit\" class=\"uk-button uk-width-1-1 bg-zinc-50 text-zinc-900 border border-zinc-50 hover:bg-zinc-900 hover:text-zinc-50\">Apply Filters</button></div><div class=\"mt-3\"><button type=\"reset\" class=\"uk-button uk-width-1-1 border border-zinc-50 hover:bg-zinc-50 hover:text-zinc-900\">Reset Filters</button></div></form><div class=\"uk-divider-vertical min-h-full\"></div></div><div class=\"col-span-4 flex flex-col\" id=\"tickets\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if search_type == "All Ticket Search" {
				templ_7745c5c3_Err = Tickets(models.GetAllTickets()).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if search_type == "Unassigned Tickets" {
				templ_7745c5c3_Err = Tickets(models.GetTeamsUnassignedTickets(current_user.Team_ID.UUID.String())).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if search_type == "Team Tickets" && user_type == "manager" {
				templ_7745c5c3_Err = Tickets(models.GetTeamTickets(current_user.Team_ID.UUID.String())).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Navbar(user_type).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
